// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nskg.Data;

#nullable disable

namespace Nskg.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501201149_AddAuditFieldsToACPARA")]
    partial class AddAuditFieldsToACPARA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nskg.Models.AcPara", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ACTYPE");

                    b.Property<string>("Cocode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GLChart1Id")
                        .HasColumnType("int");

                    b.Property<int?>("GLChart3Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Opening")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Parent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActypeCode");

                    b.HasIndex("GLChart1Id");

                    b.HasIndex("GLChart3Id");

                    b.ToTable("AcPara");
                });

            modelBuilder.Entity("Nskg.Models.AccCat", b =>
                {
                    b.Property<string>("CatCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CATCODE");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("CoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("COCODE");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CatCode");

                    b.ToTable("ACCCAT", "NSKG");
                });

            modelBuilder.Entity("Nskg.Models.Actype", b =>
                {
                    b.Property<string>("ACTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ACTYPE");

                    b.Property<string>("ACNAME")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ACNAME");

                    b.Property<string>("COCODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("COCODE");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ACTYPE");

                    b.ToTable("ACTYPE");
                });

            modelBuilder.Entity("Nskg.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Nskg.Models.ChallanDet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BilNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BillTiAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("BillTiDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("BillTiNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CartType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CartType2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CartType3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cartage1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cartage2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cartage3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ChallanHeadId")
                        .HasColumnType("int");

                    b.Property<string>("Cnacel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CommPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CusAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DCNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescYn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DisAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fooder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InvDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InvNo")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Labour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Lifter2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NetAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherEx")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PaidAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PartyEx")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Qty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RefDocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefDocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("STax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STaxAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STaxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ToPaidAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrName3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transporter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transporter2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transporter3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WhIt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WhItAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WhItAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("WhItRec")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WhSt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WhStAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WhStAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("WhStRec")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChallanHeadId");

                    b.ToTable("ChallanDet");
                });

            modelBuilder.Entity("Nskg.Models.ChallanHead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BillTiAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ChalNo")
                        .HasColumnType("int");

                    b.Property<string>("CoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DeliveryAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DeliveryAmt2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescYn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Driver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LocalAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LocalAmt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NetAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OtherEx2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PExpAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PExpAmt2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PExpAmt3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PExpBilti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PExpBilti2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PExpBilti3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PExpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PExpCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PExpCode3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyEx2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyStationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Station")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotBillTi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotLifter2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotOtherEx")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotPartyEx")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotToPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransId")
                        .HasColumnType("int");

                    b.Property<string>("Transporter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChallanHead");
                });

            modelBuilder.Entity("Nskg.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cocode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Nskg.Models.FinancialYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("FinancialYears");
                });

            modelBuilder.Entity("Nskg.Models.GLChart1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AC1")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ACCCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BSSQ")
                        .HasColumnType("int");

                    b.Property<string>("CType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncBal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Opening")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PLSQ")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrevBal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubCatCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GLChart1");
                });

            modelBuilder.Entity("Nskg.Models.GLChart3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AC1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AC2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AC3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Add1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Add2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Add3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Bharti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CHName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CRDays")
                        .HasColumnType("int");

                    b.Property<string>("CType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Closing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommExp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommExp2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommExp3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CommPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrBill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrRec")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GLChart1Id")
                        .HasColumnType("int");

                    b.Property<string>("IncBal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OPComm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OPComm2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OPComm3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Opening")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PrevBal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rate2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STaxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TR_DRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TR_LRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TR_RRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WH_IT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WH_IT_ACC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WH_ST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WH_ST_ACC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GLChart1Id");

                    b.ToTable("GLChart3");
                });

            modelBuilder.Entity("Nskg.Models.GLTrans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContraAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Docdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RefId")
                        .HasColumnType("int");

                    b.Property<string>("RefType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Votype")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GLTrans");
                });

            modelBuilder.Entity("Nskg.Models.IssDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccCode")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Amount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmtNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("BilNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BillTiNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Comm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Comm2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Comm3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CusCode")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("CusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Fooder")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FormulaCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal?>("Freight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FyId")
                        .HasColumnType("int");

                    b.Property<string>("IName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IType")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("InvDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("IssHeadId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal?>("PCommPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PackingN")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Packs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QtyPerPack")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefDocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefDocNo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("STax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STaxAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("IssHeadId");

                    b.ToTable("ISSDETAIL");
                });

            modelBuilder.Entity("Nskg.Models.IssHead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcType")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("AccCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("BCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("BilNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BillTiNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cancel")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CartType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CartType2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CartType3")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Cartage1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cartage2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cartage3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CoCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal?>("CommPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CusAdd")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CusCode")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("CusName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CusTel")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DCNO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescYN")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("DescYN1")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal?>("DisAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fooder")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FooderCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("FyId")
                        .HasColumnType("int");

                    b.Property<string>("IName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InvDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InvNo")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Labour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Lifter2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NTN")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Narration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("NetAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherEx")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PType")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("PartyEx")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefDocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefDocNo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("STax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STaxAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STaxNo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SendTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("T_T")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrName2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrName3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Transporter")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Transporter2")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Transporter3")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("WH_IT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WH_IT_Acc")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal?>("WH_IT_Amt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("WH_IT_Rec")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WH_ST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WH_ST_Acc")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal?>("WH_ST_Amt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("WH_ST_Rec")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StationId");

                    b.ToTable("ISSHEAD");
                });

            modelBuilder.Entity("Nskg.Models.OpeningBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OpeningBalances");
                });

            modelBuilder.Entity("Nskg.Models.Security.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Nskg.Models.Security.RoleFormPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleFormPermissions");
                });

            modelBuilder.Entity("Nskg.Models.UserCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserCompanies");
                });

            modelBuilder.Entity("Nskg.Models.VoDet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ac1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ac2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ac3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Actype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Billtino")
                        .HasColumnType("int");

                    b.Property<int?>("Bilno")
                        .HasColumnType("int");

                    b.Property<string>("Cancel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ChqDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Chqno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CrDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cramt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ctype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Dramt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ERate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Hacc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Invdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Invno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ncramt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ndramt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Payment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ptax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Qtyin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Qtyout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Refno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transporter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Userid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicleno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VoHeadId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Vodate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Votype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gl3Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoHeadId");

                    b.HasIndex("gl3Id");

                    b.ToTable("VoDet");
                });

            modelBuilder.Entity("Nskg.Models.VoHead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ac1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ac2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ac3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Actype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cancel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cocode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Diff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Entries")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpDays")
                        .HasColumnType("int");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<string>("Haccode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Hcramt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hdramt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Invdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Invno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partycode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Totcramt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Totdramt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Totptax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Userid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Vodate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vono2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Votype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gl3Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("gl3Id");

                    b.ToTable("VoHead");
                });

            modelBuilder.Entity("Nskg.Models.VoucherTypeSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowMultiLine")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoBalance")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBankRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VoucherTypeSettings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nskg.Models.AcPara", b =>
                {
                    b.HasOne("Nskg.Models.Actype", "Actype")
                        .WithMany("acParas")
                        .HasForeignKey("ActypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nskg.Models.GLChart1", "GLChart1")
                        .WithMany("acParas")
                        .HasForeignKey("GLChart1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nskg.Models.GLChart3", "GLChart3")
                        .WithMany("acParas")
                        .HasForeignKey("GLChart3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Actype");

                    b.Navigation("GLChart1");

                    b.Navigation("GLChart3");
                });

            modelBuilder.Entity("Nskg.Models.ChallanDet", b =>
                {
                    b.HasOne("Nskg.Models.ChallanHead", "ChallanHead")
                        .WithMany("Details")
                        .HasForeignKey("ChallanHeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChallanHead");
                });

            modelBuilder.Entity("Nskg.Models.FinancialYear", b =>
                {
                    b.HasOne("Nskg.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Nskg.Models.GLChart3", b =>
                {
                    b.HasOne("Nskg.Models.GLChart1", "GLChart1")
                        .WithMany("GLChart3s")
                        .HasForeignKey("GLChart1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GLChart1");
                });

            modelBuilder.Entity("Nskg.Models.IssDetail", b =>
                {
                    b.HasOne("Nskg.Models.IssHead", "IssHead")
                        .WithMany("Details")
                        .HasForeignKey("IssHeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssHead");
                });

            modelBuilder.Entity("Nskg.Models.IssHead", b =>
                {
                    b.HasOne("Nskg.Models.GLChart3", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nskg.Models.GLChart3", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Nskg.Models.VoDet", b =>
                {
                    b.HasOne("Nskg.Models.VoHead", "VoHead")
                        .WithMany("Details")
                        .HasForeignKey("VoHeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nskg.Models.GLChart3", "gl3")
                        .WithMany()
                        .HasForeignKey("gl3Id");

                    b.Navigation("VoHead");

                    b.Navigation("gl3");
                });

            modelBuilder.Entity("Nskg.Models.VoHead", b =>
                {
                    b.HasOne("Nskg.Models.GLChart3", "gl3")
                        .WithMany()
                        .HasForeignKey("gl3Id");

                    b.Navigation("gl3");
                });

            modelBuilder.Entity("Nskg.Models.Actype", b =>
                {
                    b.Navigation("acParas");
                });

            modelBuilder.Entity("Nskg.Models.ChallanHead", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Nskg.Models.GLChart1", b =>
                {
                    b.Navigation("GLChart3s");

                    b.Navigation("acParas");
                });

            modelBuilder.Entity("Nskg.Models.GLChart3", b =>
                {
                    b.Navigation("acParas");
                });

            modelBuilder.Entity("Nskg.Models.IssHead", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Nskg.Models.VoHead", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
